# Generated by Django 4.2.dev20221222094112 on 2023-11-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custusers',
            name='appoint_date',
            field=models.DateField(),
        ),
    ]
